#!/usr/bin/python3
"""the script will factorize a set of num in file to product of two small nums"""
from sys import argv


def factorize_func(unkown_num):
    """"get two small nums and multiply to get another num"""
    i = 2

    if unkown_num < 2:
        return
    
    while unkown_num % i:
        i += 1
    print("{:.0f}={:.0f}*{:.0f}".format(unkown_num, unkown_num / i, i))

if len(argv) != 2:
    exit()

try:
    with open(argv[1]) as file:
        ln = file.readline()

        while ln != "":
            unkown_num = int(line.split('\n')[0])
            factorize_func(unkown_num)
            line = file.readline()
except:
    pass
