#!/usr/bin/python3
"""This factorizes nums in a file to products of two small numbers."""
from sys import argv

def factorize_func(unknown_num):
    """Get two small numbers and multiply to get another number."""
    if unknown_num < 2:
        return

    i = 2
    while i * i <= unknown_num:
        if unknown_num % i:
            i += 1
        else:
            unknown_num //= i
            print(f"{unknown_num * i} = {unknown_num} * {i}")

    if unknown_num > 1:
        print(f"{unknown_num} = {unknown_num} * 1")

if len(argv) != 2:
    exit("Usage: ./script.py filename")

try:
    with open(argv[1]) as file:
        for line in file:
            unknown_num = int(line.strip())
            factorize_func(unknown_num)
except Exception as e:
    print(f"An error occurred: {e}")
