#!/usr/bin/python3
"""
factorize func that gets nums in a file into a product of 2 prime nums
"""
import sys

def factorize_func():
    """
    A factorize the given nums to two prime nums using (format n = p*q)
    """
    try:
        file = sys.argv[1]
        with open(file) as f:
            for line_number in f:
                line_number = int(line_number)
                if line_number % 2 == 0:
                        print("{}={}*{}".format(line_number, line_number // 2, 2))
                        continue
                i = 3
                while i < line_number // 2:
                    if line_number % i == 0:
                        print("{}={}*{}".format(line_number, line_number // i, i))
                        break
                    i = i + 2
                if i == (line_number // 2) + 1:
                    print("{}={}*{}".format(line_number, line_number, 1))
    except (IndexError):
        pass


factorize_func()
