#!/usr/bin/python3
"""
Factorize a unkown_num num into two prime numbers p and q.
"""

import sys

def is_prime(unkown_num):
    """Check if a unkown_num is prime."""
    if unkown_num <= 1:
        return False
    if unkown_num <= 3:
        return True
    if unkown_num % 2 == 0 or unkown_num % 3 == 0:
        return False
    i = 5
    while i * i <= unkown_num:
        if unkown_num % i == 0 or unkown_num % (i + 2) == 0:
            return False
        i += 6
    return True

def factorize_func():
    """Factorize the given numbers into two prime numbers p and q."""
    try:
        file_name = sys.argv[1]
        with open(file_name) as file:
            for line_number in file:
                num = int(line_number)
                if num % 2 == 0:
                    p = 2
                    q = num // 2
                else:
                    i = 3
                    while True:
                        if num % i == 0 and is_prime(i):
                            p = i
                            q = num // i
                            break
                        i += 2
                
                if is_prime(p) and is_prime(q):
                    print(f"{num} = {p} * {q}")

    except (IndexError, ValueError, FileNotFoundError):
        pass

factorize_func()

